name = "carleson"
defaultTargets = ["Carleson"]

[leanOptions]
relaxedAutoImplicit = false
pp.unicode.fun = true
autoImplicit = false
weak.linter.flexible = true # no rigid tactic (e.g. `exact`) after a flexible tactic (e.g. `simp`)
# Enable all mathlib linters: automatically matches what mathlib uses.
weak.linter.mathlibStandardSet = true
# Disable the long line linter, for now.
weak.linter.style.longLine = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.24.0"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"
rev = "master"

[[lean_lib]]
name = "Carleson"
